export const GLOBAL_KEYS = Object.freeze({
  USER_KEY: 'User',
  MAX_QUANTITY: 99,
  MIN_QUANTITY: 0,

  // UI keys
  ICON_SIZE_SMALL: 18,
  ICON_SIZE_DEFAULT: 24,
  ICON_SIZE_LARGE: 28,

  BORDER_RADIUS_DEFAULT: 6,
  BORDER_RADIUS_LARGE: 20,
  PADDING_DEFAULT: 16,
  PADDING_SMALL: 8,

  TEXT_SIZE_SMALL: 12,
  TEXT_SIZE_DEFAULT: 16,
  TEXT_SIZE_TITLE: 20,
  TEXT_SIZE_HEADER: 24,

  GAP_DEFAULT: 16,
  GAP_SMALL: 8,

  LIGHT_HEIGHT_DEFAULT: 20,
});
